language: c++

script:
  - scons build/X86/gem5.$VARIANT --ignore-style -j3

dist: "trusty"

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - VARIANT=opt

    - os: osx
      osx_image: xcode8
      env:
        - VARIANT=fast

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - VARIANT=fast

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - VARIANT=opt

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - VARIANT=opt
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - VARIANT=fast

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - VARIANT=opt
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - VARIANT=fast

    # works on Precise and Trusty
    - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-6
           - swig
           - libprotobuf-dev
           - python-protobuf
           - protobuf-compiler
           - libgoogle-perftools-dev
     env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
       - VARIANT=opt
    - os: linux
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-7
           - swig
           - libprotobuf-dev
           - python-protobuf
           - protobuf-compiler
           - libgoogle-perftools-dev
     env:
       - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
       - VARIANT=fast

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - VARIANT=opt
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - VARIANT=fast

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - VARIANT=opt
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        - VARIANT=fast

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - VARIANT=opt
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - swig
            - libprotobuf-dev
            - python-protobuf
            - protobuf-compiler
            - libgoogle-perftools-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        - VARIANT=fast

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install google-perftools ;fi
  - eval "${MATRIX_EVAL}"
